name: Publish
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish
    environment: prod
    env:
      AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
      AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
      DIGITALOCEAN_TOKEN: "${{ secrets.DIGITALOCEAN_TOKEN }}"
    steps:
      - name: Clone Code
        uses: actions/checkout@4.2.2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2
      - name: Init Terraform
        working-directory: terraform
        run: terraform init -input=false
      - name: Lint Terraform
        working-directory: terraform
        run: terraform fmt -check -recursive
      - name: Validate Terraform
        working-directory: terraform
        run: terraform validate
      - name: Apply
        working-directory: terraform
        run: terraform apply -input=false -auto-approve
