name: Pull Request
on:
  pull_request:
    branches: [ main ]
  merge_group:
    branches: [ main ]
permissions:
  pull-requests: write
  contents: read
jobs:
  pr-verify:
    runs-on: ubuntu-latest
    name: PR Verify
    env:
      AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
      AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
      DIGITALOCEAN_TOKEN: "${{ secrets.DIGITALOCEAN_TOKEN }}"
    steps:
      - name: Clone Code
        uses: actions/checkout@v4.2.2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2
      - name: Init Terraform
        working-directory: terraform
        run: terraform init -input=false
      - name: Lint Terraform
        working-directory: terraform
        run: terraform fmt -check -recursive
      - name: Validate Terraform
        working-directory: terraform
        run: terraform validate
      - name: Plan Terraform
        working-directory: terraform
        run: terraform plan -no-color
      - name: Show Terraform
        working-directory: terraform
        run: terraform show -no-color -json > tfplan.json
      - name: Comment Changes
        uses: liatrio/terraform-change-pr-commenter@v1.5.0
        with:
          expand-comment: 'true'
          include-plan-job-summary: 'true'
          json-file: 'terraform/tfplan.json'
